### ISSUE TITLE
Permission problem

### ISSUE THREAD

**Issue by Tontonitch** [willemdh/check_ms_iis_application_pool#2]
Hello,

I tried to use the plugin but i'm facing a permission issue.
The message returned is:
![image](https://user-images.githubusercontent.com/600025/30483811-9032a190-9a28-11e7-803f-21d8cf781028.png)
Checking the command directly on the IIS hosting server show that it works in cmd "as Administrator", but not in a standard cmd:
![image](https://user-images.githubusercontent.com/600025/30483771-68a14438-9a28-11e7-987a-de529dc47b34.png)

The Icinga2 service which is responsible of running the command runs with "Log On As Nework Service".

I don't want to another account to run the Icinga2 service. Is there a solution in order to run this plugin with such an account?

BR,
Yannick

**Comment by Tontonitch** [comment]
As a workaround, I switched to "Log On As Local System".
But I would prefer a more secure solution

**Comment by willemdh** [comment]
Well I'm running it with NSClient++ which runs as SYSTEM. Works fine there. i'm not really planning to provide a solution for this issue, so I'm closing it. Thanks for reporting though!
